language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t bohdaninhliziian/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bohdaninhliziian/react-test npm test

after_success:
  - docker build -t bohdaninhliziian/multi-client ./client
  - docker build -t bohdaninhliziian/multi-server ./server
  - docker build -t bohdaninhliziian/multi-worker ./worker
  - docker build -t bohdaninhliziian/multi-nginx ./nginx
  # login to Docker gub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push to Docker hub
  - docker push bohdaninhliziian/multi-client
  - docker push bohdaninhliziian/multi-server
  - docker push bohdaninhliziian/multi-worker
  - docker push bohdaninhliziian/multi-nginx
